name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Build app
        run: ./gradlew :app:testFullDebugUnitTest :app:assembleFullRelease

      # Sign APK and create release for tags

      - name: Prepare build metadata
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LISTEN-moe/android-app'
        run: |
          set -x
          VERSION_TAG="${GITHUB_REF/refs\/tags\//}"
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV
          if [[ "$VERSION_TAG" == *beta* ]] || [[ "$VERSION_TAG" == *alpha* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LISTEN-moe/android-app'
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          releaseDirectory: app/build/outputs/apk/full/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'LISTEN-moe/android-app'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.VERSION_TAG }}
          body_path: distribution/whatsnew/whatsnew-en-US
          files: |
            ${{ env.SIGNED_RELEASE_FILE }}
          draft: true
          prerelease: ${{ env.IS_PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: Upload APK
Uses: actions/upload-artifact@v4

:android-app-APK
:app/build/outputs/apk/release/*.apk
