name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build app
        run: ./gradlew :app:assembleFullRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app-APK
          path: app/build/outputs/apk/full/release/*.apk
